config/routes.rb
BookManager::Application.routes.draw do
  resources :books
  resources :authors
  resources :publishers
  resources :genres
  resources :subgenres

  resources :order_details
  resources :orders
  resources :price_histories
  
  get "reports" => "reports#index"

end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  desc       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Genre < ActiveRecord::Base
  attr_accessible :name, :desc

  has_many :subgenres, :inverse_of => :genre, :dependent => :destroy
  has_many :books, :inverse_of=> :genre, :dependent => :destroy

  validates :name, :presence => true,
      :length => { :maximum => 200}

  validates :desc, :presence => true,
      :length => { :maximum => 200}

  def count_books_in_genre_key
    "genre_#{id}_total_books"
  end

        
  def count_books_in_genre
    Rails.cache.fetch(count_books_in_genre_key) do
      self.books.count
    end
  end


end

app/controllers/genres_controller.rb
class GenresController < ApplicationController
  before_filter :find_genre_by_id, :only => [:edit, :update, :show, :destroy]

  def new
    @genre = Genre.new
  end

  def create
    @genre = Genre.create!(params[:genre])
  end

  def edit
  end

  def update
    @genre.update_attributes(params[:genre])
  end

  def show
  end

  def index
    @genres = Genre.all
  end

  def destroy
    @genre.destroy
  end

  private

  def find_genre_by_id
    @genre = Genre.find(params[:id])
  end

end

app/helpers/genres_helper.rb
module GenresHelper
end

app/views/genres/_form.erb
<% genre ||= @genre %>

<div class = "container">
  <%= form_for genre, :remote => true do |g| %>
    <div class = "textfield">
      <%= g.label :name %>
      <%= g.text_field :name %>
    </div>
    <div class = "textfield">
      <%= g.label :desc %>
      <%= g.text_field :desc %>
    </div>
    <%= g.submit %>
  <% end %>
</div>

app/views/genres/_genre.erb
<%
   genre ||= @genre
%>

<tr id = "<%= genre.id %>">
  <td><%= link_to genre.name, edit_genre_path(genre), :remote => true %></td>
  <td><%= genre.desc %></td>
  <td><%= link_to "delete", genre, :method => :delete, :confirm => "Are you sure?" ,:remote => true%></td>
</tr>

app/views/genres/_new.html.erb
<div class = "container">
  <%= form_for @genre do |g| %>
    <div class = "textfield">
      <%= g.label :name %>
      <%= g.text_field :name %>
    </div>
    <div class = "textfield">
      <%= g.label :desc %>
      <%= g.text_field :desc %>
    </div>
    <%= g.submit %>
  <% end %>
</div>

app/views/genres/create.js.erb
$("tbody").append("<%= escape_javascript(render "genre") %>")
$("#form_container").empty();

app/views/genres/destroy.js.erb
$("tr[id='<%= @genre.id %>']").remove();

app/views/genres/edit.js.erb
$("#form_container").html("<%= escape_javascript(render 'form') %>")

app/views/genres/index.html.erb
<%
    @genres ||= Genre.all
%>

<html>
<table border = '1'>
  <thead>
    <tr>
      <td>Name</td>
      <td>Description</td>
      <td>Action</td>
    </tr>
  </thead>
  <tbody>
    <%= render @genres %>
  </tbody>
</table>
<%= link_to "add", new_genre_path, :remote => true %><br>
<div id = "form_container"></div>
</html>

app/views/genres/new.js.erb
$("#form_container").html("<%= escape_javascript(render 'form') %>");

app/views/genres/show.html.erb
<html>
<%= javascript_include_tag :defaults %>
<table border = "1">
  <tr>
    <td>Name</td>
    <td>Description</td>
  </tr>
  <tr>
    <td><%= @genre.name %></td>
    <td><%= @genre.desc %></td>
  </tr>
</table>
<%= link_to "List", genres_path %>
<%= link_to "edit", edit_genre_path %>
<%= link_to "delete", @genre, :method => :delete, :confirm => "Are you sure?" %>
</html>

app/views/genres/update.js.erb
$("tr[id=<%= @genre.id %>]").replaceWith('<%= escape_javascript(render "genre") %>');
$("#form_container").empty();