config/routes.rb
BookManager::Application.routes.draw do
  resources :books
  resources :authors
  resources :publishers
  resources :genres
  resources :subgenres

  resources :order_details
  resources :orders
  resources :price_histories
  
  get "reports" => "reports#index"

end

app/models/author.rb
# == Schema Information
#
# Table name: authors
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  DOB        :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Author < ActiveRecord::Base
  has_many :books, :inverse_of => :author, :dependent => :destroy

  attr_accessible :first_name, :last_name, :DOB, :name

  validates :first_name, :presence => true,
      :length => { :maximum => 100}
  validates :last_name, :presence => true,
      :length => { :maximum => 100}
  validates :DOB, :presence => true,
      :length => { :is => 10}

  after_save :expire_author_cached
  after_destroy :expire_author_cached

  def name
    "#{first_name} #{last_name}"
  end

  def name=(n)
    x,y = n.split(' ')
    self.first_name = x
    self.last_name = y
    self.first_name && self.last_name
  end

  def to_s
    name
  end

  def self.all_cached
    Rails.cache.fetch('Authors.all') do
      all
    end
  end

  private

  def expire_author_cached
    Rails.cache.delete('Author.all')
  end


end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  before_filter :find_author_by_id, :only => [:show, :edit, :update, :destroy]

  def new
    @author = Author.new
  end

  def create
    @author = Author.create(params[:author])
  end

  def edit
  end

  def update
    @author.update_attributes(params[:author])
  end

  def show
  end

  def index
    @authors = Author.all_cached
  end

  def destroy
    Author.destroy(params[:id])
  end

  private

  def find_author_by_id
    @author = Author.find(params[:id])
  end

end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_author.html.erb
<%
  author ||= @author;
%>

<tr id="<%= author.id %>">
  <td><%= link_to author.name, edit_author_path(author),:remote=>true %></td>
  <td><%= author.DOB %></td>
  <td><%= link_to "delete",author, :method => :delete, :remote=>true, :confirm=>"Are you sure?" %></td>
</tr>

app/views/authors/_form.html.erb
<div content= "container">
  <%= form_for @author, :remote => true do |b| %>
    <div content = "field">
      <%= b.label :name %>
      <%= b.text_field :name %>
    </div>
    <div content = "field">
      <%= b.label :DOB %>
      <%= b.text_field :DOB %>
    </div>
    <%= b.submit %>
  <% end %>
</div>

app/views/authors/_index.html.erb
<html>
<table border="1">
  <thead>
    <tr>
      <th>Full Name</th>
      <th>Date of Birth</th>
    </tr>
  </thead>
  <tbody>
    <%= render @authors %>
  </tbody>
</table>
<div id="form_container"></div>
</html>

app/views/authors/_new.html.erb
<div content= "container">
  <%= form_for @author do |b| %>
    <div content = "field">
      <%= b.label :name %>
      <%= b.text_field :name %>
    </div>
    <div content = "field">
      <%= b.label :DOB %>
      <%= b.text_field :DOB %>
    </div>
    <%= b.submit %>
  <% end %>
</div>

app/views/authors/create.js.erb
$("tbody").append('<%= escape_javascript(render "author") %>');
$("#form_container").empty();

app/views/authors/destroy.js.erb
$("tr#<%= @author.id %>").remove();

app/views/authors/edit.html.erb
<html>
<h1>Edit</h1>
<%= render "form" %>
</html>

app/views/authors/edit.js.erb
$("#form_container").html('<%= escape_javascript(render "form") %>');

app/views/authors/index.html.erb
<html>
<%= render "index" %>
<p><%= link_to "Add", new_author_path, :remote=>true %></p>
</html>

app/views/authors/new.html.erb
<html>
<h1>Add</h1>
<%= render "form" %>
</html>

app/views/authors/new.js.erb
$("#form_container").html('<%= escape_javascript(render "form") %>');

app/views/authors/show.html.erb
<html>
<%= javascript_include_tag :defaults %>
<table border = '1'>
  <tr>
    <td>First Name</td>
    <td>Last Name</td>
    <td>Date of Birth</td>
  </tr>
  <tr>
    <td><%= @author.first_name %></td>
    <td><%= @author.last_name %></td>
    <td><%= @author.DOB %></td>
  </tr>
</table>
<%= link_to "Show all authors", authors_path %>
<%= link_to "edit", edit_author_path %>
<%= link_to "delete", @author,:method => :delete, :confirm => "Are you sure?" %>
</html>

app/views/authors/update.js.erb
$("tr#<%= @author.id %>").replaceWith('<%= escape_javascript(render "author") %>');
$("#form_container").empty()