config/routes.rb
BookManager::Application.routes.draw do
  resources :books
  resources :authors
  resources :publishers
  resources :genres
  resources :subgenres

  resources :order_details
  resources :orders
  resources :price_histories
  
  get "reports" => "reports#index"

end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id            :integer          not null, primary key
#  total_price   :float
#  customer_name :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#

class Order < ActiveRecord::Base

  attr_accessible :total_price, :customer_name, :created_at

  has_many :order_details, :inverse_of => :order, :dependent => :destroy

  validates :total_price, :numericality => true
  validates :customer_name, :presence => true,
              :length => { :maximum => 200 }

  after_create do |rec|
    rec.calculate_total
  end

  def calculate_total
    total = 0
    order_details.each do |od|
      total += od.quantity * od.unit_price
    end
    update_attributes(:total_price => total)
    true
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  before_filter :find_order_by_id, :only => [:edit, :show, :destroy]

  def new
    @order = Order.new;
  end

  def create
    @order = Order.create params[:order]
  end

  def edit
  end

  def update
    @order.update_attributes(params[:order])
  end

  def show
  end

  def index
    @orders = Order.all
  end

  def destroy
    @order.destroy;
  end

  private

  def find_order_by_id
    @order = Order.find(params[:id])
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_order.html.erb
<%
   order ||= @order
%>

<tr id = "<%= order.id %>">
  <td><%= order.customer_name%></td>
  <td><%= number_with_precision(order.total_price, :precision => 2) %></td>
  <td><%= order.created_at %></td>
  <td><%= link_to "Details", edit_order_path(order) %></td>
  <td><%= link_to "Delete", order, :method => :delete, :remote => true %></td>
</tr>

app/views/orders/_order_form.html.erb
<%
   order ||= @order
%>

<%= form_for order, :remote => true do |o| %>
  <div content = "field">
    <%= o.label :Customer_Name %>
    <%= o.text_field :customer_name %>
  </div>
  <div content = "field">
    <%= o.hidden_field :total_price, :value => '0.00' %>
  </div>
  <%= o.submit %>
<% end %>

app/views/orders/create.js.erb
$("#order_table tbody").append("<%= j(render 'order') %>")
$("#form_for_order").empty()

app/views/orders/destroy.js.erb
$("tr#<%= @order.id %>").remove()

app/views/orders/edit.html.erb
<!DOCTYPE html>
<html>
  <table id="order_detail_table", border = "1">
    <thead>
      <tr>
        <td>Book Name</td>
        <td>Quantity</td>
        <td>Actions</td>
      </tr>
    </thead>
    <tdata>
      <%= render @order.order_details %>
    </tdata>
  </table>
  <%= link_to "Add", new_order_detail_path(:order_id => @order.id), :remote => true %>
  <div id = "order_detail_form"></div>
  <%= link_to "Back", orders_path %>
</html>

app/views/orders/index.html.erb
<!DOCTYPE html>
<html>
<table border = "1" id = "order_table">
  <thead>
    <tr>
      <th>Customer Name</th>
      <th>Total Price</th>
      <th>Created At</th>
    </tr>
  </thead>
  <tbody>
    <%= render @orders %>
  </tbody>
</table>
<%= link_to "Place a new order", new_order_path, :remote => true %>
<div id="form_for_order"></div>

</html>

app/views/orders/new.js.erb
$("#form_for_order").html('<%= j(render "order_form") %>')

app/views/orders/show.html.erb
<!DOCTYPE html>
<html>

<%=
    order ||= @order
%>

<table border = "1" id="order_detail">
  <thead>
    <tr>
      <td>Book</td>
      <td>Price</td>
      <td>Quantity</td>
    </tr>
  </thead>
  <tbody>
    <%=
        @order_details = @order.order_details
        render @order_details
    %>
  </tbody>
</table>

</html>