config/routes.rb
BookManager::Application.routes.draw do
  resources :books
  resources :authors
  resources :publishers
  resources :genres
  resources :subgenres

  resources :order_details
  resources :orders
  resources :price_histories
  
  get "reports" => "reports#index"

end

app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  year         :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  author_id    :integer
#  subgenre_id  :integer
#  publisher_id :integer
#  price        :float
#

class Book < ActiveRecord::Base
  attr_accessible :name, :year, :author_id, :subgenre_id, :publisher_id, :price, :genre_id

  belongs_to :author, :inverse_of => :books
  belongs_to :subgenre, :inverse_of => :books
  belongs_to :genre, :inverse_of=> :books
  belongs_to :publisher, :inverse_of => :books
  has_many :order_details, :inverse_of => :book, :dependent => :destroy
  has_many :price_histories, :inverse_of => :book, :dependent => :destroy
  has_many :reviews, :inverse_of => :book, :dependent => :destroy

  #delegate :genre, :to => :subgenre

  validates :name, :presence => true,
            :length => { :maximum => 200 }
  validates :year, :presence => true,
            :length => { :minimum => 1 , :maximum => 4}
  validates :author_id, :presence => true
  validates :subgenre_id, :presence => true
  validates :publisher_id, :presence => true
  validates :price, :presence => true,
                    :numericality => true

  before_save :record_old_price

  before_save do |rec|
    if rec.subgenre_id_changed?
      rec.genre_id = rec.subgenre.genre_id
    end
  end

  after_save :invalid_books_in_genre_cache
  after_destroy :invalid_books_in_genre_cache

  after_save :invalid_books_in_subgenre_cache
  after_destroy :invalid_books_in_subgenre_cache

  def invalid_books_in_genre_cache
    Rails.cache.delete(genre.count_books_in_genre_key)
  end

  def invalid_books_in_subgenre_cache
    Rails.cache.delete(subgenre.count_books_in_subgenre_key)
  end

  def avg_rating_cache_key
    "book.#{id}.avg_rating"
  end

  def avg_rating
    Rails.cache.fetch(avg_rating_cache_key) do
      reviews.average(:rating)
    end
  end

  def total_volume_sold_cache_key
    "book.#{id}.total_volume"
  end

  def total_volume_sold
    Rails.cache.fetch(total_volume_sold_cache_key) do
      self.order_details.sum(:quantity)
    end
  end

  def to_s
    name
  end

  private

  def record_old_price
    if(!(new_record?) && price_changed?)
      PriceHistory.create(:book_id => self.id, :old_price => price_was, :new_price => price)
    end
    true
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_filter :find_book_by_id, :only => [:edit, :update, :show, :destroy]

  def new
    @book = Book.new
  end

  def create
    @book = Book.create params[:book]
  end

  def edit
  end

  def update
    @book.update_attributes(params[:book])
  end

  def show
  end

  def destroy
    @book.destroy
  end

  def index
    @books = Book.all
  end

  private

  def find_book_by_id
    @book = Book.find(params[:id])
  end


end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.erb
<% book ||= @book %>
<li><p class="book_name"><%= book.name %></p></li>

app/views/books/_book_list.js.erb
var bookList = new List(
  'books_list',
  {
    valueNames: ['book_name'],
    plugins: [ ]
  }
);

app/views/books/_form.erb
<%
  book ||= @book
%>
<div content= "container">
  <%= form_for book, :remote => true  do |b|%>
    <div content = "field">
      <%= b.label :name %>
      <%= b.text_field :name %>
    </div>
    <div content = "field">
      <%= b.label :year %>
      <%= b.text_field :year %>
    </div>
    <div content = "field">
      <%= b.label :author %>
      <%= b.collection_select :author_id, Author.all, :id, :name %>
    </div>
    <div content = "field" >
      <%= b.label :subgenre %>
      <%= b.collection_select :subgenre_id, Subgenre.all, :id, :name %>
    </div>
    <div content = "field" >
      <%= b.label :publisher %>
      <%= b.collection_select :publisher_id, Publisher.all, :id, :name %>
    </div>
    <div content = "field" >
      <%= b.label :price %>
      <%= b.text_field :price, :value => number_with_precision(b.object.price, :precision => 2) %>
    </div>
    <%= link_to "Back", books_path %>
    <%= b.submit %>
  <% end %>
</div>

app/views/books/_index.html.erb
<div class = "books_list" id="books_list">
  <input type="text" class="search" />
  <ol class = "list" size=6>
    <%= render @books %>
  </ol>
</div>

app/views/books/_new.html.erb
<div content= "container">
  <%= form_for @book do |b| %>
    <div content = "field">
      <%= b.label :name %>
      <%= b.text_field :name %>
    </div>
    <div content = "field">
      <%= b.label :year %>
      <%= b.text_field :year %>
    </div>
    <div content = "field">
      <%= b.label :author %>
      <%= b.collection_select :author_id, Author.all, :id, :name %>
    </div>
    <%= b.submit %>
  <% end %>
</div>

app/views/books/create.js.erb
$("#book_table > tbody").append('<%= escape_javascript(render "book") %>');
$("#form_container").empty();

app/views/books/destroy.js.erb
$('tr[data-book-id="<%= @book.id %>"]').remove();

app/views/books/edit.erb
<!DOCTYPE HTML>
<html>
<%= render "form" %>
</html>

app/views/books/edit.js.erb
$('#form_container').html('<%= escape_javascript(render 'form') %>');

app/views/books/index.html.erb
<!--
<html>
<head>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
<script src="
https://cdnjs.cloudflare.com/ajax/libs/list.js/1.1.1/list.min.js"></script>
</head>
<%= render "index" %>
<script><%= render "book_list.js" %></script>
<%= link_to "Add", new_book_path, remote: true %>

<div id="form_container">
</div>
</html>
-->
<%= render "shared/book.html.erb" %>

app/views/books/new.js.erb
$('#form_container').html('<%= escape_javascript(render 'form') %>');

app/views/books/show.html.erb
<html>
<%= javascript_include_tag :defaults %>
<table border = '1'>
  <tr>
    <td>Name</td>
    <td>Year</td>
    <td>Author</td>
    <td>Sub Genre</td>
    <td>Publisher</td>
  </tr>
  <tr>
    <td><%= @book.name %></td>
    <td><%= @book.year %></td>
    <td><%= @book.author %></td>
    <td><%= @book.subgenre.name %></td>
    <td><%= @book.publisher.name %></td>
  </tr>
</table>
<%= link_to "List", books_path %><br>
<%= link_to "Edit", edit_book_path %>
<%= link_to "Delete", @book, :method => :delete, :confirm => "Are you sure?" %>
</html>

app/views/books/show.json.erb
<%= @book.to_json %>

app/views/books/update.js.erb
$("tr[data-book-id=<%= @book.id %>]").replaceWith('<%= escape_javascript(render "book") %>');
$("#form_container").empty();